### ISSUE TITLE
How to compile Align1D?

### ISSUE THREAD

**Issue by yangjiangeyjg** [sauradip/fewshotQAT#1]
How to compile Align1D?  @sauradip 
Thanks!

**Comment by sauradip** [comment]
Hi @yangjiangeyjg , since Align1D is part of GTAD ( the base encoder we have used in this paper ) , i would refer you to the processing of this paper here : https://github.com/frostinassiky/gtad

**Comment by yangjiangeyjg** [comment]
> Hi @yangjiangeyjg , since Align1D is part of GTAD ( the base encoder we have used in this paper ) , i would refer you to the processing of this paper here : https://github.com/frostinassiky/gtad

Thanks very much!
