### ISSUE TITLE
Python 2.7 or 3.7

### ISSUE THREAD

**Issue by Quadwo** [sauradip/fewshotQAT#2]
I have an issue with gtad lib -- I created two envs FSQAT(2.7) and GTAD(3.7) - I cannot install the aign1d on GTAD(3.7) is my issue. I have seen the error only appears in python 3.7. Below are some screenshots from my pc.
![Screenshot from 2021-12-30 13-31-43](https://user-images.githubusercontent.com/29419645/147725441-c9507b20-83b3-4967-8eab-d5abdc72cee7.png)

![Screenshot from 2021-12-30 13-32-12](https://user-images.githubusercontent.com/29419645/147725408-7d2b15ee-a94e-4e2f-babb-58435c8db989.png)
![Screenshot from 2021-12-30 13-38-41](https://user-images.githubusercontent.com/29419645/147725418-9995ff7d-f026-4222-a2d3-90ad8d8758f4.png)
![Screenshot from 2021-12-30 13-30-13](https://user-images.githubusercontent.com/29419645/147725436-5f6405a9-10b6-444f-ad2b-508a0ff81bbc.png)

**Comment by Quadwo** [comment]
Your assistance will be greatly appreciated. thanks

**Comment by sauradip** [comment]
Hi @Quadwo , 

This part of the code is borrowed from https://github.com/frostinassiky/gtad where it works for python 3.7 ! However, i can suspect one problem is may be you can try making the cpp freshly ! It might happen that the directory already has an already prepared cpp for align , and when you again run the installer , it checks for this prepapred file and might skip the preparation process ! I would suggest , clean install ( by clean i mean delete the  folder also ) and then try it !

It should work ! My environment was 3.7 it worked !

**Comment by Quadwo** [comment]
Alright... thanks. I'll do that and tell you my progress.

**Comment by sauradip** [comment]
I guess your environment issue is solved ! If not feel free to reopen
