### ISSUE TITLE
no moudle named visdom_logger

### ISSUE THREAD

**Issue by mugenggeng** [sauradip/fewshotQAT#3]
![image](https://user-images.githubusercontent.com/87792372/150666832-89db62a4-496c-403e-b3c9-aef5944ea53a.png)

**Comment by sauradip** [comment]
Hi,

Kindly install this visdom logger using the following command , I think you will good to go ! 

`pip install git+https://github.com/luizgh/visdom_logger.git`

Let me know if you need help

**Comment by mugenggeng** [comment]
thanks，but I still ran into new problems
<img width="371" alt="1643280245(1)" src="https://user-images.githubusercontent.com/87792372/151343596-f9df9014-1b5a-4c69-a6e9-f942b668a54e.png">

**Comment by sauradip** [comment]
Hi,

Due to the file-size i could not upload this file . You can find it here : https://drive.google.com/file/d/1--d6V5xeVWznO0cPI_47f5wWGL8RO6P0/view?usp=sharing. Download and place in "data" folder. 

Let me know if it helps

**Comment by mugenggeng** [comment]
thanks
| |
Tender
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/28/2022 08:02，Sauradip ***@***.***> wrote：

Hi,

Due to the file-size i could not upload this file . You can find it here : https://drive.google.com/file/d/1--d6V5xeVWznO0cPI_47f5wWGL8RO6P0/view?usp=sharing. Download and place in "data" folder.

Let me know if it helps

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mugenggeng** [comment]
![image](https://user-images.githubusercontent.com/87792372/151656708-52e214cb-1b4f-410f-87bd-76d60cf78b58.png)
Is there something wrong with this? Valid_mode can never be "Standard ".

**Comment by sauradip** [comment]
Standard Validation mode refers to the actual supervised setting. Since this is few-shot setting, it can never be a standard Validation,  the implementation of meta-learning is done during inference. Hence we need to change this.

**Comment by sauradip** [comment]
Feel free to reopen this issue if issue persist ! After your doubts I feel you could run the code successfully so closing this issue
