### ISSUE TITLE
align1d error

### ISSUE THREAD

**Issue by Quadwo** [sauradip/fewshotQAT#5]
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

can you help with this?

**Comment by sauradip** [comment]
This looks like a torch version mismatch ! Kindly check the requirements in ReadME 
Have a look at this thread : https://github.com/frostinassiky/gtad/issues/20#issuecomment-652997019

Our code is borrowed from GTAD

**Comment by sauradip** [comment]
Feel free to re-open if not resolved
