### ISSUE TITLE
GTAD checkpoint

### ISSUE THREAD

**Issue by lucky-23** [sauradip/fewshotQAT#6]
Hello, I am unable to run align.py due to incompatibility issue with my CUDA/CUDNN version and I have been stuck with this problem for a long time. Can you please share the pre-trained weights of GTAD model on ActivityNet dataset?
Thank you very much!

**Comment by lucky-23** [comment]
And also in the paper you compared with BMN(Boundary matching)  as an embedding module. I would be grateful if you could kindly let me know from which layer did you extract the features from the pre-trained BMN model?
Thank you!.

**Comment by sauradip** [comment]
> Hello, I am unable to run align.py due to incompatibility issue with my CUDA/CUDNN version and I have been stuck with this problem for a long time. Can you please share the pre-trained weights of GTAD model on ActivityNet dataset? Thank you very much!

Here is the [checkpoint](https://drive.google.com/drive/folders/19d4thM_ywioMpkzAWUM0LEdyneL59_CF) for your convenience

**Comment by sauradip** [comment]
> And also in the paper you compared with BMN(Boundary matching) as an embedding module. I would be grateful if you could kindly let me know from which layer did you extract the features from the pre-trained BMN model? Thank you!.

We took the output of this 3d conv block https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/a92c1d79c19d88b1d57b5abfae5a0be33f3002eb/models.py#L71

**Comment by lucky-23** [comment]
Thank you very much!
